from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Any

from fastapi import APIRouter

router = APIRouter(prefix="/colab", tags=["colab"])


@dataclass
class ColabEnvironment:
    python_version: str = "3.11+"
    frameworks: list[str] = None
    instructions: str = ""

    def __post_init__(self):
        if self.frameworks is None:
            self.frameworks = ["pandas", "scikit-learn", "fairlearn", "shap", "xgboost"]


_COLAB_BOILERPLATE = """\
# ──────────────────────────────────────────────────────────
# BIAS Colab Export — Generated by Unbiased AI Platform
# ──────────────────────────────────────────────────────────
# Run this cell to install dependencies:
# !pip install pandas scikit-learn fairlearn shap xgboost matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from fairlearn.metrics import MetricFrame, demographic_parity_difference, equalized_odds_difference
"""


@router.get("/export")
async def export_colab_notebook() -> dict[str, Any]:
    env = ColabEnvironment()
    return {
        "environment": asdict(env),
        "notebook": _COLAB_BOILERPLATE,
        "cells": [
            {"type": "code", "source": _COLAB_BOILERPLATE},
        ],
    }
